# 应用名称
spring:
  application:
    name: Admin-server
    #邮件设置
  mail:
    host: smtp.qq.com
      #单纯的qq号
    username: 834031172
      #生成的授权码
    password: royyvdhedstqbffh
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
  #收件邮箱
  boot:
    admin:
      notify:
        mail:
          #收件邮箱
          to: 834031172@qq.com
          # 发件邮箱
          from: 834031172@qq.com
logging:
  level:
    root: info