# 应用名称
server:
  port: 81
spring:
  application:
    name: OpenFeign-API
eureka:
  client:
    service-url:
      #配置注册地址
      defaultZone: http://localhost:7900/eureka/
logging:
  level:
    root: info