eureka:
  client:
    service-url:
      #配置注册地址
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: api-provider
  boot:
    admin:
      client:
        url: http://localhost:8080
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always

---
spring:
  profiles:
    active: 9110
server:
  port: 9110

---
spring:
  profiles: 9111
server:
  port: 9111
---
spring:
  profiles: 9112
server:
  port: 9112