# 应用名称
spring:
  application:
    name: zuulserver
eureka:
  client:
    service-url:
      #配置注册地址
      defaultZone: http://localhost:7900/eureka/
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include:
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true

